### ISSUE TITLE
Resources for TS in Julia

### ISSUE THREAD

**Issue by azev77** [Stellenbosch-Econometrics/AdvancedTimeSeries-872#1]
Hi & thanks for post your material! 
You might wanna check out my working list:
https://discourse.julialang.org/t/time-series-in-julia-working-list/62539?u=albert_zevelev

**Comment by DawievLill** [comment]
No problem. It is still quite incomplete, but at least it is a start. 

Thanks for the the list, some really useful resources on there. Really good initiative on your part.
